# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer_files/search.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_search(object):
    def setupUi(self, search):
        search.setObjectName(_fromUtf8("search"))
        search.resize(585, 346)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(search.sizePolicy().hasHeightForWidth())
        search.setSizePolicy(sizePolicy)
        search.setMinimumSize(QtCore.QSize(461, 346))
        self.gridLayout_5 = QtGui.QGridLayout(search)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 1, 1)
        self.search_frame = QtGui.QFrame(search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_frame.sizePolicy().hasHeightForWidth())
        self.search_frame.setSizePolicy(sizePolicy)
        self.search_frame.setMinimumSize(QtCore.QSize(182, 260))
        self.search_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.search_frame.setObjectName(_fromUtf8("search_frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.search_frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.search_frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lblSrchStatus = QtGui.QLabel(self.search_frame)
        self.lblSrchStatus.setObjectName(_fromUtf8("lblSrchStatus"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblSrchStatus)
        self.label2 = QtGui.QLabel(self.search_frame)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2)
        self.lblStatusDir = QtGui.QLabel(self.search_frame)
        self.lblStatusDir.setObjectName(_fromUtf8("lblStatusDir"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblStatusDir)
        self.gridLayout_3.addLayout(self.formLayout, 2, 4, 1, 1)
        self.btnSRCPOS = QtGui.QPushButton(self.search_frame)
        self.btnSRCPOS.setObjectName(_fromUtf8("btnSRCPOS"))
        self.gridLayout_3.addWidget(self.btnSRCPOS, 4, 2, 1, 1)
        self.btnSRCHSTAT = QtGui.QPushButton(self.search_frame)
        self.btnSRCHSTAT.setObjectName(_fromUtf8("btnSRCHSTAT"))
        self.gridLayout_3.addWidget(self.btnSRCHSTAT, 2, 2, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.search_frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lblSrchPos = QtGui.QLabel(self.search_frame)
        self.lblSrchPos.setObjectName(_fromUtf8("lblSrchPos"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblSrchPos)
        self.label2_2 = QtGui.QLabel(self.search_frame)
        self.label2_2.setObjectName(_fromUtf8("label2_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2_2)
        self.lblSrchEnc = QtGui.QLabel(self.search_frame)
        self.lblSrchEnc.setObjectName(_fromUtf8("lblSrchEnc"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblSrchEnc)
        self.gridLayout_3.addLayout(self.formLayout_2, 4, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.search_frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 5)
        self.line_3 = QtGui.QFrame(self.search_frame)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(100, 16))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.comboEDGETYPE = QtGui.QComboBox(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboEDGETYPE.sizePolicy().hasHeightForWidth())
        self.comboEDGETYPE.setSizePolicy(sizePolicy)
        self.comboEDGETYPE.setMinimumSize(QtCore.QSize(70, 22))
        self.comboEDGETYPE.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboEDGETYPE.setFont(font)
        self.comboEDGETYPE.setObjectName(_fromUtf8("comboEDGETYPE"))
        self.comboEDGETYPE.addItem(_fromUtf8(""))
        self.comboEDGETYPE.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboEDGETYPE, 1, 1, 1, 1)
        self.comboSRCHDIR = QtGui.QComboBox(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSRCHDIR.sizePolicy().hasHeightForWidth())
        self.comboSRCHDIR.setSizePolicy(sizePolicy)
        self.comboSRCHDIR.setMinimumSize(QtCore.QSize(70, 22))
        self.comboSRCHDIR.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboSRCHDIR.setFont(font)
        self.comboSRCHDIR.setObjectName(_fromUtf8("comboSRCHDIR"))
        self.comboSRCHDIR.addItem(_fromUtf8(""))
        self.comboSRCHDIR.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboSRCHDIR, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(100, 16))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.comboSRCHSIG = QtGui.QComboBox(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSRCHSIG.sizePolicy().hasHeightForWidth())
        self.comboSRCHSIG.setSizePolicy(sizePolicy)
        self.comboSRCHSIG.setMinimumSize(QtCore.QSize(70, 22))
        self.comboSRCHSIG.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboSRCHSIG.setFont(font)
        self.comboSRCHSIG.setObjectName(_fromUtf8("comboSRCHSIG"))
        self.comboSRCHSIG.addItem(_fromUtf8(""))
        self.comboSRCHSIG.addItem(_fromUtf8(""))
        self.comboSRCHSIG.addItem(_fromUtf8(""))
        self.comboSRCHSIG.addItem(_fromUtf8(""))
        self.comboSRCHSIG.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboSRCHSIG, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(100, 16))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.btnSearch = QtGui.QPushButton(self.search_frame)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.gridLayout_3.addWidget(self.btnSearch, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboSRCHENC_sel = QtGui.QComboBox(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSRCHENC_sel.sizePolicy().hasHeightForWidth())
        self.comboSRCHENC_sel.setSizePolicy(sizePolicy)
        self.comboSRCHENC_sel.setMinimumSize(QtCore.QSize(70, 22))
        self.comboSRCHENC_sel.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboSRCHENC_sel.setFont(font)
        self.comboSRCHENC_sel.setObjectName(_fromUtf8("comboSRCHENC_sel"))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.comboSRCHENC_sel.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboSRCHENC_sel, 1, 1, 1, 1)
        self.comboSRCHPOS_sel = QtGui.QComboBox(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboSRCHPOS_sel.sizePolicy().hasHeightForWidth())
        self.comboSRCHPOS_sel.setSizePolicy(sizePolicy)
        self.comboSRCHPOS_sel.setMinimumSize(QtCore.QSize(70, 22))
        self.comboSRCHPOS_sel.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.comboSRCHPOS_sel.setFont(font)
        self.comboSRCHPOS_sel.setObjectName(_fromUtf8("comboSRCHPOS_sel"))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.comboSRCHPOS_sel.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboSRCHPOS_sel, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(100, 16))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.search_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(100, 16))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.search_frame, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)

        self.retranslateUi(search)
        QtCore.QMetaObject.connectSlotsByName(search)

    def retranslateUi(self, search):
        search.setWindowTitle(_translate("search", "Dialog", None))
        self.label.setText(_translate("search", "Status:", None))
        self.lblSrchStatus.setText(_translate("search", "?", None))
        self.label2.setText(_translate("search", "Direction:", None))
        self.lblStatusDir.setText(_translate("search", "?", None))
        self.btnSRCPOS.setText(_translate("search", "Query Position", None))
        self.btnSRCHSTAT.setText(_translate("search", "Query Status", None))
        self.label_2.setText(_translate("search", "Axis:", None))
        self.lblSrchPos.setText(_translate("search", "?", None))
        self.label2_2.setText(_translate("search", "Encoder:", None))
        self.lblSrchEnc.setText(_translate("search", "?", None))
        self.label_9.setText(_translate("search", "Search signal", None))
        self.comboEDGETYPE.setItemText(0, _translate("search", "POSEDGE", None))
        self.comboEDGETYPE.setItemText(1, _translate("search", "NEGEDGE", None))
        self.comboSRCHDIR.setItemText(0, _translate("search", "+1", None))
        self.comboSRCHDIR.setItemText(1, _translate("search", "-1", None))
        self.label_11.setText(_translate("search", "Search direction", None))
        self.comboSRCHSIG.setItemText(0, _translate("search", "Lim-", None))
        self.comboSRCHSIG.setItemText(1, _translate("search", "Lim+", None))
        self.comboSRCHSIG.setItemText(2, _translate("search", "Home", None))
        self.comboSRCHSIG.setItemText(3, _translate("search", "EncAux", None))
        self.comboSRCHSIG.setItemText(4, _translate("search", "InpAux", None))
        self.label_10.setText(_translate("search", "Edge type", None))
        self.btnSearch.setText(_translate("search", "Search Now", None))
        self.comboSRCHENC_sel.setItemText(0, _translate("search", "Axis", None))
        self.comboSRCHENC_sel.setItemText(1, _translate("search", "Measure", None))
        self.comboSRCHENC_sel.setItemText(2, _translate("search", "ShftEnc", None))
        self.comboSRCHENC_sel.setItemText(3, _translate("search", "TgtEnc", None))
        self.comboSRCHENC_sel.setItemText(4, _translate("search", "EncIN", None))
        self.comboSRCHENC_sel.setItemText(5, _translate("search", "InPos", None))
        self.comboSRCHENC_sel.setItemText(6, _translate("search", "AbsEnc", None))
        self.comboSRCHENC_sel.setItemText(7, _translate("search", "Motor", None))
        self.comboSRCHPOS_sel.setItemText(0, _translate("search", "Axis", None))
        self.comboSRCHPOS_sel.setItemText(1, _translate("search", "Measure", None))
        self.comboSRCHPOS_sel.setItemText(2, _translate("search", "PosErr", None))
        self.comboSRCHPOS_sel.setItemText(3, _translate("search", "ShftEnc", None))
        self.comboSRCHPOS_sel.setItemText(4, _translate("search", "TgtEnc", None))
        self.comboSRCHPOS_sel.setItemText(5, _translate("search", "EncIN", None))
        self.comboSRCHPOS_sel.setItemText(6, _translate("search", "InPos", None))
        self.comboSRCHPOS_sel.setItemText(7, _translate("search", "AbsEnc", None))
        self.comboSRCHPOS_sel.setItemText(8, _translate("search", "Motor", None))
        self.label_13.setText(_translate("search", "SRCHENC selection", None))
        self.label_12.setText(_translate("search", "SRCHPOS selection", None))

